version: '3.9'

services:
    app:
        build:
            context: .
            target: production
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=production
            - PORT=3000
            - DISCORD_CLIENT_ID=x
            - DISCORD_CLIENT_SECRET=-x
            - DISCORD_REDIRECT_URI=x
            - GOOGLE_CLIENT_ID=x
            - GOOGLE_CLIENT_SECRET=x
            - GOOGLE_REDIRECT_URI=x
            - SESSION_SECRET=x
            - JWT_SECRET=x
            - WALLET_PRIVATE_KEY=0x85167e00aeed1db6a59945f1f78f997856e2e312cf4e55cde90b740b71f9808c
            - WALLET_PUBLIC_KEY=x
            - LOG_LEVEL=info
            - FRONTEND_URL=http://localhost:3000
            - LIT_NETWORK=datil-dev
        volumes:
            - ./coverage:/project/coverage
