version: "3.9"

services:
  app:
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3000
      - GOOGLE_CLIENT_ID=x
      - GOOGLE_CLIENT_SECRET=y
      - GOOGLE_CALLBACK_URI=https://github.com/brocoders/nestjs-boilerplate/tree/main/src
      - DISCORD_CLIENT_ID=v
      - DISCORD_CLIENT_SECRET=b
      - DISCORD_CALLBACK_URI=https://github.com/brocoders/nestjs-boilerplate/tree/main/src
      - JWT_SECRET=t
      - LOG_LEVEL=trace
    volumes:
      - ./coverage:/project/coverage
