name: CI Pipeline

on:
  push:
    branches:
      - '**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml

  build-push:
    needs: [test, lint]
    uses: ./.github/workflows/build-push.yml
    with:
      REGISTRY: ${{ env.REGISTRY }}
      IMAGE_NAME: ${{ env.IMAGE_NAME }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
